/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/concepts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Concepts resources.
         * @description Retrieves the collection of Concepts resources.
         */
        get: operations["api_concepts_get_collection"];
        put?: never;
        /**
         * Creates a Concepts resource.
         * @description Creates a Concepts resource.
         */
        post: operations["api_concepts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/concepts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Concepts resource.
         * @description Retrieves a Concepts resource.
         */
        get: operations["api_concepts_id_get"];
        put?: never;
        post?: never;
        /**
         * Removes the Concepts resource.
         * @description Removes the Concepts resource.
         */
        delete: operations["api_concepts_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the Concepts resource.
         * @description Updates the Concepts resource.
         */
        patch: operations["api_concepts_id_patch"];
        trace?: never;
    };
    "/api/learning_goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of LearningGoal resources.
         * @description Retrieves the collection of LearningGoal resources.
         */
        get: operations["api_learning_goals_get_collection"];
        put?: never;
        /**
         * Creates a LearningGoal resource.
         * @description Creates a LearningGoal resource.
         */
        post: operations["api_learning_goals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning_goals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a LearningGoal resource.
         * @description Retrieves a LearningGoal resource.
         */
        get: operations["api_learning_goals_id_get"];
        put?: never;
        post?: never;
        /**
         * Removes the LearningGoal resource.
         * @description Removes the LearningGoal resource.
         */
        delete: operations["api_learning_goals_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the LearningGoal resource.
         * @description Updates the LearningGoal resource.
         */
        patch: operations["api_learning_goals_id_patch"];
        trace?: never;
    };
    "/api/learning_paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of LearningPath resources.
         * @description Retrieves the collection of LearningPath resources.
         */
        get: operations["api_learning_paths_get_collection"];
        put?: never;
        /**
         * Creates a LearningPath resource.
         * @description Creates a LearningPath resource.
         */
        post: operations["api_learning_paths_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning_paths/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a LearningPath resource.
         * @description Retrieves a LearningPath resource.
         */
        get: operations["api_learning_paths_id_get"];
        put?: never;
        post?: never;
        /**
         * Removes the LearningPath resource.
         * @description Removes the LearningPath resource.
         */
        delete: operations["api_learning_paths_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the LearningPath resource.
         * @description Updates the LearningPath resource.
         */
        patch: operations["api_learning_paths_id_patch"];
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Creates a user token.
         * @description Creates a user token.
         */
        post: operations["login_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Modules resources.
         * @description Retrieves the collection of Modules resources.
         */
        get: operations["api_modules_get_collection"];
        put?: never;
        /**
         * Creates a Modules resource.
         * @description Creates a Modules resource.
         */
        post: operations["api_modules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Modules resource.
         * @description Retrieves a Modules resource.
         */
        get: operations["api_modules_id_get"];
        put?: never;
        post?: never;
        /**
         * Removes the Modules resource.
         * @description Removes the Modules resource.
         */
        delete: operations["api_modules_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the Modules resource.
         * @description Updates the Modules resource.
         */
        patch: operations["api_modules_id_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Concepts: {
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            module?: string;
            description?: string | null;
            difficulty?: string;
            importance_score?: number;
            estimated_time?: number;
            /** Format: date-time */
            updated_at?: string;
            lessons?: components["schemas"]["Lessons"][];
            readonly id?: number;
            title?: string;
            /** Format: date-time */
            created_at?: string;
            importanceScore?: number;
            estimatedTime?: number;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        "Concepts.jsonMergePatch": {
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            module?: string;
            description?: string | null;
            difficulty?: string;
            importance_score?: number;
            estimated_time?: number;
            /** Format: date-time */
            updated_at?: string;
            lessons?: components["schemas"]["Lessons"][];
            readonly id?: number;
            title?: string;
            /** Format: date-time */
            created_at?: string;
            importanceScore?: number;
            estimatedTime?: number;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        "Concepts.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            module?: string;
            description?: string | null;
            difficulty?: string;
            importance_score?: number;
            estimated_time?: number;
            /** Format: date-time */
            updated_at?: string;
            lessons?: components["schemas"]["Lessons.jsonld"][];
            readonly id?: number;
            title?: string;
            /** Format: date-time */
            created_at?: string;
            importanceScore?: number;
            estimatedTime?: number;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description Unprocessable entity */
        ConstraintViolation: {
            /** @default 422 */
            status: number;
            violations?: {
                /** @description The property path of the violation */
                propertyPath: string;
                /** @description The message associated with the violation */
                message: string;
                /** @description The code of the violation */
                code?: string;
                /** @description An extra hint to understand the violation */
                hint?: string;
                /** @description The serialized payload of the violation */
                payload?: {
                    [key: string]: unknown;
                };
            }[];
            readonly detail?: string;
            readonly type?: string;
            readonly title?: string | null;
            readonly instance?: string | null;
        };
        /** @description Unprocessable entity */
        "ConstraintViolation.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @default 422 */
            status: number;
            violations?: {
                /** @description The property path of the violation */
                propertyPath: string;
                /** @description The message associated with the violation */
                message: string;
                /** @description The code of the violation */
                code?: string;
                /** @description An extra hint to understand the violation */
                hint?: string;
                /** @description The serialized payload of the violation */
                payload?: {
                    [key: string]: unknown;
                };
            }[];
            readonly detail?: string;
            readonly description?: string;
            readonly type?: string;
            readonly title?: string | null;
            readonly instance?: string | null;
        };
        /** @description A representation of common errors. */
        Error: {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string | null;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string | null;
            /**
             * @default 400
             * @example 404
             */
            status: number | null;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
        };
        /** @description A representation of common errors. */
        "Error.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /** @description A short, human-readable summary of the problem. */
            readonly title?: string | null;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            readonly detail?: string | null;
            /**
             * @default 400
             * @example 404
             */
            status: number | null;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            readonly instance?: string | null;
            /** @description A URI reference that identifies the problem type */
            readonly type?: string;
            readonly description?: string | null;
        };
        HydraCollectionBaseSchema: components["schemas"]["HydraCollectionBaseSchemaNoPagination"] & {
            /**
             * @example {
             *       "@id": "string",
             *       "@type": "string",
             *       "first": "string",
             *       "last": "string",
             *       "previous": "string",
             *       "next": "string"
             *     }
             */
            view?: {
                /** Format: iri-reference */
                "@id"?: string;
                "@type"?: string;
                /** Format: iri-reference */
                first?: string;
                /** Format: iri-reference */
                last?: string;
                /** Format: iri-reference */
                previous?: string;
                /** Format: iri-reference */
                next?: string;
            };
        };
        HydraCollectionBaseSchemaNoPagination: {
            totalItems?: number;
            search?: {
                "@type"?: string;
                template?: string;
                variableRepresentation?: string;
                mapping?: {
                    "@type"?: string;
                    variable?: string;
                    property?: string | null;
                    required?: boolean;
                }[];
            };
        };
        HydraItemBaseSchema: {
            "@context"?: string | ({
                "@vocab": string;
                /** @enum {string} */
                hydra: "http://www.w3.org/ns/hydra/core#";
            } & {
                [key: string]: unknown;
            });
            "@id": string;
            "@type": string;
        };
        LearningGoal: {
            description?: string | null;
            level?: string;
            status?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string | null;
            learner?: components["schemas"]["User"];
            learningPaths?: string[];
            readonly id?: number;
            title?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        "LearningGoal.jsonMergePatch": {
            description?: string | null;
            level?: string;
            status?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string | null;
            learner?: components["schemas"]["User"];
            learningPaths?: string[];
            readonly id?: number;
            title?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        "LearningGoal.jsonld": {
            learner?: components["schemas"]["User.jsonld"];
            learningPaths?: string[];
            readonly id?: number;
            title?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        } & (components["schemas"]["HydraItemBaseSchema"] & {
            description?: string | null;
            level?: string;
            status?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string | null;
        });
        LearningPath: {
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            goal?: string | null;
            description?: string | null;
            estimated_duration?: number;
            modules?: string[];
            readonly id?: number;
            title?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            estimatedDuration?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        "LearningPath.jsonMergePatch": {
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            goal?: string | null;
            description?: string | null;
            estimated_duration?: number;
            modules?: string[];
            readonly id?: number;
            title?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            estimatedDuration?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        "LearningPath.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            goal?: string | null;
            description?: string | null;
            estimated_duration?: number;
            modules?: string[];
            readonly id?: number;
            title?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            estimatedDuration?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Lessons: {
            content?: string;
            summary?: string;
            examples?: string;
            difficulty?: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            concept?: string | null;
            readonly id?: number;
            title?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        "Lessons.jsonld": {
            content?: string;
            summary?: string;
            examples?: string;
            difficulty?: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            concept?: string | null;
            readonly id?: number;
            title?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Modules: {
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            learningPath?: string;
            description?: string;
            position?: number;
            difficulty?: string;
            estimated_duration?: string | null;
            concepts?: string[];
            readonly id?: number;
            title?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            estimatedDuration?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        "Modules.jsonMergePatch": {
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            learningPath?: string;
            description?: string;
            position?: number;
            difficulty?: string;
            estimated_duration?: string | null;
            concepts?: string[];
            readonly id?: number;
            title?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            estimatedDuration?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        "Modules.jsonld": components["schemas"]["HydraItemBaseSchema"] & {
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            learningPath?: string;
            description?: string;
            position?: number;
            difficulty?: string;
            estimated_duration?: string | null;
            concepts?: string[];
            readonly id?: number;
            title?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            estimatedDuration?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        User: {
            email?: string;
            /** @description The user roles */
            roles?: string[];
            /** @description The hashed password */
            password?: string;
            learningGoals?: components["schemas"]["LearningGoal"][];
            readonly id?: number;
            /** @description A visual identifier that represents this user. */
            readonly userIdentifier?: string;
        };
        "User.jsonld": {
            email?: string;
            /** @description The user roles */
            roles?: string[];
            /** @description The hashed password */
            password?: string;
            learningGoals?: components["schemas"]["LearningGoal.jsonld"][];
            readonly id?: number;
            /** @description A visual identifier that represents this user. */
            readonly userIdentifier?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        /** Format: email */
                        email?: string;
                        roles?: string[];
                    };
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Registration data */
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description User created — returns JWT token */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                    };
                };
            };
            /** @description Email already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        errors?: {
                            [key: string]: string[];
                        };
                    };
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        errors?: {
                            [key: string]: string[];
                        };
                    };
                };
            };
        };
    };
    api_concepts_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Concepts collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["Concepts.jsonld"][];
                    };
                    "application/json": components["schemas"]["Concepts"][];
                };
            };
        };
    };
    api_concepts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new Concepts resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["Concepts"];
                "application/json": components["schemas"]["Concepts"];
            };
        };
        responses: {
            /** @description Concepts resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Concepts.jsonld"];
                    "application/json": components["schemas"]["Concepts"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_concepts_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Concepts identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Concepts resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Concepts.jsonld"];
                    "application/json": components["schemas"]["Concepts"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_concepts_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Concepts identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Concepts resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_concepts_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Concepts identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated Concepts resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["Concepts.jsonMergePatch"];
            };
        };
        responses: {
            /** @description Concepts resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Concepts.jsonld"];
                    "application/json": components["schemas"]["Concepts"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_learning_goals_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description LearningGoal collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["LearningGoal.jsonld"][];
                    };
                    "application/json": components["schemas"]["LearningGoal"][];
                };
            };
        };
    };
    api_learning_goals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new LearningGoal resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["LearningGoal"];
                "application/json": components["schemas"]["LearningGoal"];
            };
        };
        responses: {
            /** @description LearningGoal resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["LearningGoal.jsonld"];
                    "application/json": components["schemas"]["LearningGoal"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_learning_goals_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description LearningGoal identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description LearningGoal resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["LearningGoal.jsonld"];
                    "application/json": components["schemas"]["LearningGoal"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_learning_goals_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description LearningGoal identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description LearningGoal resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_learning_goals_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description LearningGoal identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated LearningGoal resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["LearningGoal.jsonMergePatch"];
            };
        };
        responses: {
            /** @description LearningGoal resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["LearningGoal.jsonld"];
                    "application/json": components["schemas"]["LearningGoal"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_learning_paths_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description LearningPath collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["LearningPath.jsonld"][];
                    };
                    "application/json": components["schemas"]["LearningPath"][];
                };
            };
        };
    };
    api_learning_paths_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new LearningPath resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["LearningPath"];
                "application/json": components["schemas"]["LearningPath"];
            };
        };
        responses: {
            /** @description LearningPath resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["LearningPath.jsonld"];
                    "application/json": components["schemas"]["LearningPath"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_learning_paths_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description LearningPath identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description LearningPath resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["LearningPath.jsonld"];
                    "application/json": components["schemas"]["LearningPath"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_learning_paths_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description LearningPath identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description LearningPath resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_learning_paths_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description LearningPath identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated LearningPath resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["LearningPath.jsonMergePatch"];
            };
        };
        responses: {
            /** @description LearningPath resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["LearningPath.jsonld"];
                    "application/json": components["schemas"]["LearningPath"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    login_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The login data */
        requestBody: {
            content: {
                "application/json": {
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description User token created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        readonly token: string;
                    };
                };
            };
        };
    };
    api_modules_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Modules collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["HydraCollectionBaseSchema"] & {
                        member: components["schemas"]["Modules.jsonld"][];
                    };
                    "application/json": components["schemas"]["Modules"][];
                };
            };
        };
    };
    api_modules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new Modules resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["Modules"];
                "application/json": components["schemas"]["Modules"];
            };
        };
        responses: {
            /** @description Modules resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Modules.jsonld"];
                    "application/json": components["schemas"]["Modules"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
    api_modules_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Modules identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Modules resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Modules.jsonld"];
                    "application/json": components["schemas"]["Modules"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_modules_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Modules identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Modules resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    api_modules_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Modules identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated Modules resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["Modules.jsonMergePatch"];
            };
        };
        responses: {
            /** @description Modules resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Modules.jsonld"];
                    "application/json": components["schemas"]["Modules"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["Error.jsonld"];
                    "application/problem+json": components["schemas"]["Error"];
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An error occurred */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["ConstraintViolation.jsonld"];
                    "application/problem+json": components["schemas"]["ConstraintViolation"];
                    "application/json": components["schemas"]["ConstraintViolation"];
                };
            };
        };
    };
}
